# Worker 名称,与CF中的Worker名称必须一致
name = "flux"

# 兼容性日期，确保使用最新的 Workers 运行时功能
compatibility_date = "2024-10-04"

# 主入口文件
main = "./build/worker/index.js"

# 静态资源目录
assets = { directory = "./build/client" }

# 启用 Workers 日志
[observability]
enabled = true

[vars]
# account_id:你的CloudFlare帐户ID
# token:有Workers AI权限的API令牌
CF_ACCOUNT_LIST = '''[{
    "account_id":"0bf323aa812939e3e37caee2aadfc2b0",
    "token":"4MPnwTI_BLshvm1QH2PecGDWtP6V-XgELnjkqk8b"
}]'''
API_KEY = "your_api_key_here"
CF_TRANSLATE_MODEL = "@cf/qwen/qwen1.5-14b-chat-awq"
CF_IS_TRANSLATE = "true"
USE_EXTERNAL_API = "false"
EXTERNAL_API = ""
EXTERNAL_MODEL = ""
EXTERNAL_API_KEY = ""
FLUX_NUM_STEPS = "4"
CUSTOMER_MODEL_MAP = '''{
    "FLUX.1-Schnell-CF":"@cf/black-forest-labs/flux-1-schnell", 
    "SD-XL-Bash-CF":"@cf/stabilityai/stable-diffusion-xl-base-1.0",
    "SD-XL-Lightning-CF":"@cf/bytedance/stable-diffusion-xl-lightning",
    "DS-8-CF":"@cf/lykon/dreamshaper-8-lcm",
    "SD-V1-5-Img2img":"@cf/runwayml/stable-diffusion-v1-5-img2img",
    "SD-V1-5-Inpainting":"@cf/runwayml/stable-diffusion-v1-5-inpainting"
}'''
getme = "测试专用"
